
spring:
  profiles: test
  thymeleaf.cache: false
  aop:
    auto: true
server:
  port: 9000
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
  eureka:
    enabled: true
zuul: 
  routes: 
    product-api:
      sensitiveHeaders:                               
      path: /api/ps/**
      stripPrefix: false
  add-proxy-headers: true
  host:
    socket-timeout-millis: 12000
    connect-timeout-millis: 12000
security:
  basic:
    enabled: false
logging:
  level.org.springframework.security: DEBUG
management:
  security:
    enabled: false
hystrix:
  threadpool: 
    default: 
      metrics:
        rollingStats:
          timeInMilliseconds: 150000
        rollingPercentile:
          numBuckets: 10
