server:
  port: 10002
spring:
  profiles: test
  application:
    name: product-service
# 连接数据库
  datasource:
    url: jdbc:postgresql://localhost:5432/sc_db
    username: postgres
    password: 123
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true
    generate-ddl: false
    properties.hibernate.show_sql: true
    properties.hibernate.dialect: org.jianhuasc.common.dao.dialect.JsonPostgreSQLDialect
    properties.hibernate.hbm2ddl.auto: update
  aop:
    auto: true
    proxy-target-class: true
